# Enable debug info in console
debug-mode: false

# Enable colors in console output
color-logs: true

# Language file (for translations)
language-file: lang-en.yml

# Allow /back command to go to last death location
back-on-death: true

# How long before teleport requests timeout (in seconds)
teleport-request-timeout: 30

# Play sound when teleporting
use-teleport-sounds: true

# Sounds to play in world when teleporting
sound-to: ENTITY_ENDERMAN_TELEPORT
sound-from: ENTITY_ENDERMAN_TELEPORT

# Allow unsafe enchantments
unsafe-enchantments: false

# Allow nicknames to be set
allow-nick: true

# Allow items to be repaired
allow-repair: true

# Selects the repair hand
# True = Repair item in main hand
# false = Repair item in off hand
repair-main-hand: false