name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
description: ${project.artifactId} Paper Plugin
author: BillyGalbreath
api-version: 1.13
softdepend:
- Vault

commands:
  pl3xcraft:
    description: Reload configs
    usage: /<command> (reload)
  back:
    description: Go back to previous location
    usage: /<command>
  delhome:
    description: Deletes a home.
    usage: /<command> [home (player)]
    aliases:
    - deletehome
  gmadventure:
    description: Set gamemode to adventure mode
    usage: /<command> (player)
    aliases:
    - gamemodeadventure
    - gma
  gmcreative:
    description: Set gamemode to creative mode
    usage: /<command> (player)
    aliases:
    - gamemodecreative
    - gmc
  gmspectator:
    description: Set gamemode to spectator mode
    usage: /<command> (player)
    aliases:
    - gamemodespectator
    - gmsp
  gmsurvival:
    description: Set gamemode to survival mode
    usage: /<command> (player)
    aliases:
    - gamemodesurvival
    - gms
  home:
    description: Teleports the player home.
    usage: /<command> (home (player))
  homes:
    description: List the player's homes.
    usage: /<command> (player)
    aliases:
    - listhomes
  jump:
    description: Go to block in line of sight
    usage: /<command>
  sethome:
    description: Sets the player's home.
    usage: /<command> (home (player))
    aliases:
    - homeset
  setspawn:
    description: Sets the server spawn point
    usage: /<command>
  spawn:
    description: Teleport to the server spawn point
    usage: /<command>
    aliases:
    - hub
    - server
  teleportaccept:
    description: Accept teleport request
    usage: /<command>
    aliases:
    - tpaccept
  teleportdeny:
    description: Decline teleport request
    usage: /<command>
    aliases:
    - tpdeny
  teleportrequest:
    description: Request to teleport to another player
    usage: /<command> player
    aliases:
    - tpa
    - tprequest
  teleportrequestall:
    description: Send teleport here request to all players
    usage: /<command>
    aliases:
    - tpaall
    - teleportrequestall
  teleportrequesthere:
    description: Request another player to teleport to you
    usage: /<command> player
    aliases:
    - tpah
    - tpahere
    - teleportrequesth
    - teleportrequesthere
  teleporttoggle:
    description: Toggle teleport requests on/off
    usage: /<command>
    aliases:
    - tpt
    - tptoggle
  top:
    description: Go to the highest block at current position
    usage: /<command>

permissions:
  command.pl3xcraft:
    description: Allows to reload configs
    default: op
  command.back:
    description: Go back to previous location
    default: op
  command.delhome:
    description: Allows the player to delete a home.
    default: op
  command.gamemode.adventure:
    description: Allows player to set own gamemode to adventure mode
    default: op
  command.gamemode.adventure.other:
    description: Allows player to set another player's gamemode to adventure mode
    default: op
  command.gamemode.creative:
    description: Allows player to set own gamemode to creative mode
    default: op
  command.gamemode.creative.other:
    description: Allows player to set another player's gamemode to creative mode
    default: op
  command.gamemode.spectator:
    description: Allows player to set own gamemode to spectator mode
    default: op
  command.gamemode.spectator.other:
    description: Allows player to set another player's gamemode to spectator mode
    default: op
  command.gamemode.survival:
    description: Allows player to set own gamemode to survival mode
    default: op
  command.gamemode.survival.other:
    description: Allows player to set another player's gamemode to survival mode
    default: op
  command.home:
    description: Allows the player to go home.
    default: op
  command.homes:
    description: Allows the player to list homes.
    default: op
  command.jump:
    description: Go to block in line of sight
    default: op
  command.sethome:
    description: Allows the player to set a home.
    default: op
    children:
      command.sethome.limit.1:
        description: Allows the player to set 1 home.
        default: true
  command.setspawn:
    description: Allows the player to set the server spawn.
    default: op
  command.spawn:
    description: Allows the player to teleport to the server spawn
    default: true
  command.teleport.override:
    description: Overrides teleport request toggle setting
    default: op
  command.teleportaccept:
    description: Accept teleport request
    default: op
  command.teleportdeny:
    description: Decline teleport request
    default: op
  command.teleportrequest:
    description: Request to teleport to another player
    default: op
  command.teleportrequestall:
    description: Send teleport here request to all players
    default: op
  command.teleportrequesthere:
    description: Request another player to teleport to you
    default: op
  command.teleporttoggle:
    description: Toggle teleport requests on/off
    default: op
  command.top:
    description: Go to highest block at current position
    default: op

  command.delhome.other:
    description: Allows the player to delete other players' homes.
    default: op
  command.home.other:
    description: Allows the player to go to other players' homes.
    default: op
  command.homes.other:
    description: Allows the player to list other players' homes.
    default: op
  command.sethome.other:
    description: Allows the player to set other players' homes.
    default: op

  command.delhome.exempt:
    description: Makes it so other players cannot delete the player's homes.
    default: false
  command.home.exempt:
    description: Makes it so other players cannot go to the player's homes.
    default: false
  command.homes.exempt:
    description: Makes it so other players cannot list the player's homes.
    default: false
  command.sethome.exempt:
    description: Makes it so other players cannot set the player's homes.
    default: false
