name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
description: ${project.artifactId} Paper Plugin
author: BillyGalbreath
api-version: 1.13
softdepend:
- DiscordSRV
- Vault

commands:
  pl3xcraft:
    description: Reload configs.
    permission: command.pl3xcraft
    usage: /<command> (reload)
  assign:
    description: Assign a command to any itme in your hand.
    permission: command.assign
    usage: /<command> [command]
    aliases:
    - powertool
    - pt
  back:
    description: Go back to previous location.
    permission: command.back
    usage: /<command>
  burn:
    description: Sets a player on fire.
    permission: command.burn
    usage: /<command> [player] (seconds)
  clearinventory:
    description: Clears your inventory.
    permission: command.clearinventory
    usage: /<command> (player)
    aliases:
    - clear
    - ci
  coords:
    description: Shows a player's coordinates and world.
    permission: command.coords
    usage: /<command> (player)
    aliases:
    - location
    - loc
    - position
    - pos
  delhome:
    description: Deletes a home.
    permission: command.delhome
    usage: /<command> [home (player)]
    aliases:
    - deletehome
  depth:
    description: Allows a player to see how far they are above/below sea level.
    permission: command.depth
    usage: /<command> (player)
  enchant:
    description: Enchants the item in hand
    permission: command.enchant
    usage: /<command> [enchantment/all] (level)
  enchantingtable:
    description: Opens an enchanting table anywhere.
    permission: command.enchantingtable
    usage: /<command>
    aliases:
    - enchantingt
    - etable
    - et
  feed:
    description: Refill hunger and saturation.
    permission: command.feed
    usage: /<command> (player)
  fly:
    description: Toggles creative flymode for yourself or another player.
    permission: command.fly
    usage: /<command> (player)
  furnace:
    description: Remotely manage a furnace you set.
    permission: command.furnace
    usage: /<command> [set/show]
  gmadventure:
    description: Set gamemode to adventure mode.
    permission: command.gamemode.adventure
    usage: /<command> (player)
    aliases:
    - gamemodeadventure
    - gma
  gmcreative:
    description: Set gamemode to creative mode.
    permission: command.gamemode.creative
    usage: /<command> (player)
    aliases:
    - gamemodecreative
    - gmc
  gmspectator:
    description: Set gamemode to spectator mode.
    permission: command.gamemode.spectator
    usage: /<command> (player)
    aliases:
    - gamemodespectator
    - gmsp
  gmsurvival:
    description: Set gamemode to survival mode.
    permission: command.gamemode.survival
    usage: /<command> (player)
    aliases:
    - gamemodesurvival
    - gms
  harm:
    description: Deals damage to a player.
    permission: command.harm
    usage: /<command> [player] (1 - 20)
  hat:
    description: Wear the Item/Block in your hand as a Hat/Helmet.
    permission: command.hat
    usage: /<command> (remove/off)
    aliases:
    - helmet
  heal:
    description: Heals yourself or another player.
    permission: command.heal
    usage: /<command> (player)
    aliases:
    - health
  home:
    description: Teleports the player home.
    permission: command.home
    usage: /<command> (home (player))
  homes:
    description: List the player's homes.
    permission: command.homes
    usage: /<command> (player)
    aliases:
    - listhomes
  jump:
    description: Go to block in line of sight.
    permission: command.jump
    usage: /<command>
  kickme:
    description: Kicks the player when command typed.
    permission: command.kickme
    usage: /<command>
    aliases:
    - login
    - nope
  killall:
    description: Kills all players online.
    permission: command.killall
    usage: /<command>
  list:
    description: Lists all users on the server.
    permission: command.list
    usage: /<command>
    aliases:
      - listplayers
      - players
      - playing
      - online
      - who
  repair:
    description: Repairs the item in your hand or another players.
    permission: command.repair
    usage: /<command> (all/player (all) )
  seen:
    description: Shows when a player was last online.
    permission: command.seen
    usage: /<command> [player]
    aliases:
      - lastseen
  sethome:
    description: Sets the player's home.
    permission: command.sethome
    usage: /<command> (home (player))
    aliases:
    - homeset
  teleportaccept:
    description: Accept teleport request.
    permission: command.teleportaccept
    usage: /<command>
    aliases:
    - tpaccept
  teleportdeny:
    description: Decline teleport request.
    permission: command.teleportdeny
    usage: /<command>
    aliases:
    - tpdeny
  teleportrequest:
    description: Request to teleport to another player.
    permission: command.teleportrequest
    usage: /<command> player
    aliases:
    - tpa
    - tprequest
  teleportrequestall:
    description: Send teleport here request to all players.
    permission: command.teleportrequestall
    usage: /<command>
    aliases:
    - tpaall
    - teleportrequestall
  teleportrequesthere:
    description: Request another player to teleport to you.
    permission: command.teleportrequesthere
    usage: /<command> player
    aliases:
    - tpah
    - tpahere
    - teleportrequesth
    - teleportrequesthere
  teleporttoggle:
    description: Toggle teleport requests on/off.
    permission: command.teleporttoggle
    usage: /<command>
    aliases:
    - tpt
    - tptoggle
  tell:
    description: Send a private message.
    permission: command.tell
    usage: /<command> [player] [message]
    aliases:
    - whisper
    - w
    - privatemessage
    - prvtmsg
    - pm
    - msg
    - send
    - m
    - t
    - emsg
    - tell
  top:
    description: Go to the highest block at current position.
    permission: command.top
    usage: /<command>
  workbench:
    description: Opens a workbench anywhere.
    permission: command.workbench
    usage: /<command>

permissions:
  command.pl3xcraft:
    description: Allows to reload configs.
    default: op
  command.assign:
    description: Assign a command to any itme in your hand.
    default: op
  command.back:
    description: Go back to previous location.
    default: op
  command.burn:
    description: Sets a player on fire.
    default: op
  command.clearinventory:
    description: Clears your inventory.
    default: op
  command.coords:
    description: Allows you to see your own coords.
    default: op
  command.delhome:
    description: Allows the player to delete a home.
    default: op
  command.depth:
    description: Allows a player to see how far they are above/below sea level.
    default: op
  command.enchant:
    description: Allows you to enchant items.
    default: op
  command.enchantingtable:
    description: Allows you to open an enchanting table anywhere.
    default: op
  command.feed:
    description: Alows you to increase your hunger.
    default: op
  command.fly:
    description: Allows you to toggle creative flymode.
    default: op
  command.furnace:
    description: Allows you to remotely manage a furnace you set.
    default: op
  command.harm:
    description: Allows you to harm a player.
    default: op
  command.hat:
    description: Allows you to wear an item/block as a ht/helmet.
    default: op
  command.heal:
    description: Allows you to heal yourself.
    default: op
  command.gamemode.adventure:
    description: Allows player to set own gamemode to adventure mode.
    default: op
  command.gamemode.adventure.other:
    description: Allows player to set another player's gamemode to adventure mode.
    default: op
  command.gamemode.creative:
    description: Allows player to set own gamemode to creative mode.
    default: op
  command.gamemode.creative.other:
    description: Allows player to set another player's gamemode to creative mode.
    default: op
  command.gamemode.spectator:
    description: Allows player to set own gamemode to spectator mode.
    default: op
  command.gamemode.spectator.other:
    description: Allows player to set another player's gamemode to spectator mode.
    default: op
  command.gamemode.survival:
    description: Allows player to set own gamemode to survival mode.
    default: op
  command.gamemode.survival.other:
    description: Allows player to set another player's gamemode to survival mode.
    default: op
  command.home:
    description: Allows the player to go home.
    default: op
  command.homes:
    description: Allows the player to list homes.
    default: op
  command.jump:
    description: Go to block in line of sight.
    default: op
  command.killall:
    description: Allows the player to kill all players online.
    default: op
  command.list:
    description: Lists all users on the server.
    default: op
  command.repair:
    description: Allows the player to repair a item(s) in their hand.
    default: op
  command.seen:
    description: Allows the player to see when another player was last online.
    default: op
  command.sethome:
    description: Allows the player to set a home.
    default: op
    children:
      command.sethome.limit.1:
        description: Allows the player to set 1 home.
        default: true
  command.teleport.override:
    description: Overrides teleport request toggle setting.
    default: op
  command.teleportaccept:
    description: Accept teleport request.
    default: op
  command.teleportdeny:
    description: Decline teleport request.
    default: op
  command.teleportrequest:
    description: Request to teleport to another player.
    default: op
  command.teleportrequestall:
    description: Send teleport here request to all players.
    default: op
  command.teleportrequesthere:
    description: Request another player to teleport to you.
    default: op
  command.teleporttoggle:
    description: Toggle teleport requests on/off.
    default: op
  command.top:
    description: Go to highest block at current position.
    default: op
  command.workench:
    description: Allows you to open a workbench anywhere.
    default: op

  command.clearinventory.other:
    description: Allows the player to clear other players inventory.
    default: op
  command.coords.other:
    description: Allows you to see the coords of another player.
    default: op
  command.delhome.other:
    description: Allows the player to delete other players' homes.
    default: op
  command.depth.other:
    description: Allows the player to see the depth of another player.
    default: op
  command.feed.other:
    description: Allows the player to increase the hunger of another player.
    default: op
  command.fly.other:
    description: Allows the player to toggle creative flymode of another player.
  command.heal.other:
    description: Allows the player to heal another player.
    default: op
  command.home.other:
    description: Allows the player to go to other players' homes.
    default: op
  command.homes.other:
    description: Allows the player to list other players' homes.
    default: op
  command.sethome.other:
    description: Allows the player to set other players' homes.
    default: op
  command.repair.other:
    description: Allows the player to repair other players' item(s).
    default: op

  command.burn.exempt:
    description: Makes it so other players cannot burn the player.
    default: false
  command.harm.exempt:
    description: Makes it so other players cannot harm the player.
    default: false
  command.delhome.exempt:
    description: Makes it so other players cannot delete the player's homes.
    default: false
  command.home.exempt:
    description: Makes it so other players cannot go to the player's homes.
    default: false
  command.homes.exempt:
    description: Makes it so other players cannot list the player's homes.
    default: false
  command.kickme.exempt:
    description: Makes it so that the player typing this command won't get kicked.
    default: op
  command.killall.exempt:
    description: Makes it so other players cannnot kill them while killall command is ran.
    default: op
  command repair.exempt:
    description: Makes it so other players cannot repair thier item(s).
    default: op
  command.sethome.exempt:
    description: Makes it so other players cannot set the player's homes.
    default: false
