name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
description: ${project.artifactId} Paper Plugin
author: BillyGalbreath
api-version: 1.13
softdepend:
- Vault

commands:
  pl3xcraft:
    description: Reload configs
    usage: /<command> (reload)
  assign:
    description: Assign a command to any itme in your hand
    usage: /<command> [command]
    aliases:
    - powertool
    - pt
  back:
    description: Go back to previous location
    usage: /<command>
  burn:
    description: Sets a player on fire
    usage: /<command> [player] (seconds)
  broadcast:
    description: Broadcasts a message to all players
    usage: /<command> [message]
    aliases:
    - say
  clearinventory:
    description: Clears your inventory
    usage: /<command> (player)
    aliases:
    - clear
    - ci
  coords:
    description: Shows a player's coordinates and world
    usage: /<command> (player)
    aliases:
    - location
    - loc
    - position
    - pos
  delhome:
    description: Deletes a home.
    usage: /<command> [home (player)]
    aliases:
    - deletehome
  depth:
    description: Allows a player to see how far they are above/below sea level.
    usage: /<command> (player)
  enchant:
    description: Enchants the item in hand
    usage: /<command> [enchantment/all] (level)
  enchantingtable:
    description: Opens an enchanting table anywhere.
    usage: /<command>
    aliases:
    - enchantingt
    - etable
    - et
  enderchest:
    description: Opens your enderchest anywhere.
    usage: /<command> (player)
    aliases:
    - enderc
    - echest
    - ec
  feed:
    description: Increase your hunger or another players.
    usage: /<command> (player / amount) (otherPlayersAmount)
  fly:
    description: Toggles creative flymode for yourself or another player
    usage: /<command> (player)
  furnace:
    description: Remotely manage a furnace you set.
    usage: /<command> [set/show]
  gmadventure:
    description: Set gamemode to adventure mode
    usage: /<command> (player)
    aliases:
    - gamemodeadventure
    - gma
  gmcreative:
    description: Set gamemode to creative mode
    usage: /<command> (player)
    aliases:
    - gamemodecreative
    - gmc
  gmspectator:
    description: Set gamemode to spectator mode
    usage: /<command> (player)
    aliases:
    - gamemodespectator
    - gmsp
  gmsurvival:
    description: Set gamemode to survival mode
    usage: /<command> (player)
    aliases:
    - gamemodesurvival
    - gms
  harm:
    description: Deals damae to a player
    usage: /<command> [player] (1 - 20)
  hat:
    description: Wear the Item/Block in your hand as a Hat/Helmet.
    usage: /<command> (remove/off)
    aliases:
    - helmet
  heal:
    description: Heals yuorself or another palyer.
    usage: /<command> (player)
    aliases:
    - health
  home:
    description: Teleports the player home.
    usage: /<command> (home (player))
  homes:
    description: List the player's homes.
    usage: /<command> (player)
    aliases:
    - listhomes
  invmod:
    description: Modifies other players; inventories.
    usage: /<command> (player)
  jump:
    description: Go to block in line of sight
    usage: /<command>
  killall:
    description: Kills all players online.
    usage: /<command>
  nick:
    description: Sets a nickname.
    usage: /<command>
  repair:
    description: Repairs the item in your hand or another palyers.
    usage: /<command> (all/player (all) )
  sethome:
    description: Sets the player's home.
    usage: /<command> (home (player))
    aliases:
    - homeset
  setspawn:
    description: Sets the server spawn point
    usage: /<command>
  spawn:
    description: Teleport to the server spawn point
    usage: /<command>
    aliases:
    - hub
    - server
  teleportaccept:
    description: Accept teleport request
    usage: /<command>
    aliases:
    - tpaccept
  teleportdeny:
    description: Decline teleport request
    usage: /<command>
    aliases:
    - tpdeny
  teleportrequest:
    description: Request to teleport to another player
    usage: /<command> player
    aliases:
    - tpa
    - tprequest
  teleportrequestall:
    description: Send teleport here request to all players
    usage: /<command>
    aliases:
    - tpaall
    - teleportrequestall
  teleportrequesthere:
    description: Request another player to teleport to you
    usage: /<command> player
    aliases:
    - tpah
    - tpahere
    - teleportrequesth
    - teleportrequesthere
  teleporttoggle:
    description: Toggle teleport requests on/off
    usage: /<command>
    aliases:
    - tpt
    - tptoggle
  top:
    description: Go to the highest block at current position
    usage: /<command>

permissions:
  command.pl3xcraft:
    description: Allows to reload configs
    default: op
  command.assign:
    description: ssign a command to any itme in your hand
    default: op
  command.back:
    description: Go back to previous location
    default: op
  command.broadcast:
    description: Broadcast message
    default: op
  command.burn:
    description: Sets a player on fire
    default: op
  command.clearinventory:
    description: Clears your inventory
    default: op
  command.coords:
    description: Allows you to see your own coords
    default: op
  command.delhome:
    description: Allows the player to delete a home.
    default: op
  command.depth:
    description: Allows a player to see how far they are above/below sea level
    default: op
  command.enchant:
    description: Allows you to enchant items.
    default: op
  command.enchantingtable:
    description: Allows you to open an enchanting table anywhere.
    default: op
  command.enderchest:
    description: Allows you to open an enderchest anywhere.
    default: op
  command.feed:
    description: Alows you to increase your hunger.
    default: op
  command.fly:
    description: Allows you to toggle creative flymode.
    default: op
  command.furnace:
    description: Allows you to remotely manage a furnace you set.
    default: op
  command.harm:
    description: Allows you to harm a player
    default: op
  command.hat:
    description: Allows you to wear an item/block as a ht/helmet.
    default: op
  command.heal:
    description: Allows you to heal yourself.
    default: op
  command.gamemode.adventure:
    description: Allows player to set own gamemode to adventure mode
    default: op
  command.gamemode.adventure.other:
    description: Allows player to set another player's gamemode to adventure mode
    default: op
  command.gamemode.creative:
    description: Allows player to set own gamemode to creative mode
    default: op
  command.gamemode.creative.other:
    description: Allows player to set another player's gamemode to creative mode
    default: op
  command.gamemode.spectator:
    description: Allows player to set own gamemode to spectator mode
    default: op
  command.gamemode.spectator.other:
    description: Allows player to set another player's gamemode to spectator mode
    default: op
  command.gamemode.survival:
    description: Allows player to set own gamemode to survival mode
    default: op
  command.gamemode.survival.other:
    description: Allows player to set another player's gamemode to survival mode
    default: op
  command.home:
    description: Allows the player to go home.
    default: op
  command.homes:
    description: Allows the player to list homes.
    default: op
  command.invmod:
    description: Allows the player to modify another palyers inventory.
    default: op
  command.jump:
    description: Go to block in line of sight
    default: op
  command.killall:
    description: Allows the player to kill all players online.
    default: op
  command.nick:
    description: Allows the player to set a nickname.
    default: op
  command.repair:
    description: Allows the player to repair a item(s) in their hand
    default: op
  command.sethome:
    description: Allows the player to set a home.
    default: op
    children:
      command.sethome.limit.1:
        description: Allows the player to set 1 home.
        default: true
  command.setspawn:
    description: Allows the player to set the server spawn.
    default: op
  command.spawn:
    description: Allows the player to teleport to the server spawn
    default: true
  command.teleport.override:
    description: Overrides teleport request toggle setting
    default: op
  command.teleportaccept:
    description: Accept teleport request
    default: op
  command.teleportdeny:
    description: Decline teleport request
    default: op
  command.teleportrequest:
    description: Request to teleport to another player
    default: op
  command.teleportrequestall:
    description: Send teleport here request to all players
    default: op
  command.teleportrequesthere:
    description: Request another player to teleport to you
    default: op
  command.teleporttoggle:
    description: Toggle teleport requests on/off
    default: op
  command.top:
    description: Go to highest block at current position
    default: op

  command.clearinventory.other:
    description: Allows the player to clear other players inventory.
    default: op
  command.coords.other:
    description: Allows you to see the coords of another player.
    default: op
  command.delhome.other:
    description: Allows the player to delete other players' homes.
    default: op
  command.depth.other:
    description: Allows the player to see the depth of another player.
    default: op
  command.enderchest.other:
    description: Allows the player to see the enderchest of another player.
    default: op
  command.feed.other:
    description: Allows the player to increase the hunger of another player.
    default: op
  command.fly.other:
    description: Allows the player to toggle creative flymode of another player.
  command.heal.other:
    description: Allows the player to heal another player.
    default: op
  command.home.other:
    description: Allows the player to go to other players' homes.
    default: op
  command.homes.other:
    description: Allows the player to list other players' homes.
    default: op
  command.sethome.other:
    description: Allows the player to set other players' homes.
    default: op
  command.nick.other:
    description: Allows the player to set other players' nickname.
    default: op
  command.repair.other:
    description: Allows the player to repair other players' item(s).
    default: op

  command.burn.exempt:
    description: Makes it so other players cannot burn the player.
    default: false
  command.harm.exempt:
    description: Makes it so other players cannot harm the player.
    default: false
  command.delhome.exempt:
    description: Makes it so other players cannot delete the player's homes.
    default: false
  command.home.exempt:
    description: Makes it so other players cannot go to the player's homes.
    default: false
  command.homes.exempt:
    description: Makes it so other players cannot list the player's homes.
    default: false
  command.invmod.exempt:
    description: Makes it so other players cannot modify the player's inventory.
    default: op
  command.killall.exempt:
    description: Makes it so other players cannnot kill them while killall command is ran.
    default: op
  command.nick.exempt:
    description: Makes it so other players cannot set their nickname.
    default: op
  command repair.exempt:
    description: Makes it so other players cannot repair thier item(s).
    default: op
  command.sethome.exempt:
    description: Makes it so other players cannot set the player's homes.
    default: false
